CREATE TABLE to_do (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner VARCHAR(255),
    title VARCHAR(255),
    description VARCHAR(255),
    status VARCHAR(50),
    created_at DATE,
    completed_at DATE
);